* Encoding: UTF-8.
GET FILE='p:\BP.sav'.

EXAMINE VARIABLES=obese BY sexnr
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL.

GRAPH
  /HISTOGRAM(NORMAL)=obese
  /PANEL ROWVAR=sexnr ROWOP=CROSS.


EXAMINE VARIABLES=obese BY bp
  /PLOT=BOXPLOT
  /STATISTICS=NONE
  /NOTOTAL.

GRAPH
  /HISTOGRAM(NORMAL)=bp
  /PANEL ROWVAR=sexnr ROWOP=CROSS.

GRAPH
  /SCATTERPLOT(BIVAR)=obese WITH bp BY sexnr
  /MISSING=LISTWISE.

